name: Continuous Integration & Deployment
on:
  push:
    branches:
      - main
    paths:
      - "**Dockerfile**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch codebase
        uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"

      - name: Restore Dependencies
        run: dotnet restore BaristaApi

      - name: Build Api
        run: dotnet build -c Release --no-restore BaristaApi

      - name: Run Unit Tests
        run: dotnet test -c Release BaristaTests

      - uses: actions/upload-artifact@main
        with:
          name: webpack artifacts
          path: BaristaApi/

  docker-build-and-push:
    runs-on: ubuntu-latest
    name: Docker Build & Push
    needs: build
    steps:
      - name: Fetch codebase
        uses: actions/checkout@v1

      - name: Download built artifact
        uses: actions/download-artifact@main
        with:
          name: webpack artifacts
          path: BaristaApi

      - name: Build container image
        uses: docker/build-push-action@v1
        with:
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
          registry: docker.pkg.github.com
          repository: adambrodin/the-barista-api-team-1/barista-api
          tag_with_sha: true
