name: Continuous Integration & Deployment
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetches codebase
        uses: actions/checkout@v2

      - name: Setup Dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0"

      - name: Restore Dependencies
        run: dotnet restore BaristaApi

      - name: Build Project
        run: dotnet build -c Release --no-restore BaristaApi
